repos:
  # Ruff - Python linting and formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.1
    hooks:
      - id: ruff
        name: ruff (lint)
        args: [--fix, --exit-non-zero-on-fix]
        types_or: [python, pyi]
      - id: ruff-format
        name: ruff (format)
        types_or: [python, pyi]

  # MyPy - Type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        name: mypy (type check)
        args: [--ignore-missing-imports, --no-error-summary]
        additional_dependencies:
          - azure-functions
          - azure-cosmos
          - pydantic>=2.0
        files: ^src/functions/

  # General pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^notebooks/
      - id: end-of-file-fixer
        exclude: ^notebooks/
      - id: check-yaml
        args: [--unsafe]
      - id: check-json
      - id: check-added-large-files
        args: [--maxkb=1000]
      - id: check-merge-conflict
      - id: detect-private-key
      - id: no-commit-to-branch
        args: [--branch, main, --branch, master]

  # Bicep linting (requires bicep CLI installed)
  - repo: local
    hooks:
      - id: bicep-build
        name: bicep (validate)
        entry: bash -c 'for f in "$@"; do bicep build "$f" --stdout > /dev/null; done' --
        language: system
        files: \.bicep$
        pass_filenames: true

  # Check for secrets
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: (\.lock$|\.ipynb$)

# CI configuration
ci:
  autofix_prs: true
  autoupdate_schedule: weekly
  skip: [bicep-build, mypy]  # Skip in CI (handled by workflow)
